import { Logo } from './logo'

export type LegalDocument = 'privacy' | 'terms'

function PrivacyPolicy() {
  return <>
    <p>Sted is operated by <strong>Finiks Labs LLC</strong>, a Wyoming limited liability company (“Finiks Labs,” “Sted,” “we,” “us,” or “our”).</p>
    <p>This Privacy Policy explains how we collect, use, disclose, and protect information when you use the Sted iOS application, its Share Extension, sted.ai, and related services (collectively, the “Service”).</p>

    <h2>1. What Sted does</h2>
    <p>Sted helps you save and organize links.</p>
    <p>When you save a link to Sted, Sted may retrieve information associated with that link and use automated systems, including artificial intelligence, to generate information such as summaries, tags, topics, and project organization. The saved link and information generated from it are associated with your private Sted account.</p>
    <p>The current Sted application does not provide direct uploads of photographs, screenshots, raw video files, camera captures, microphone recordings, or arbitrary personal files.</p>

    <h2>2. Information we collect</h2>
    <h3>Account information</h3>
    <p>Sted uses Sign in with Apple for authentication.</p>
    <p>Depending on the information you choose to share through Apple, we may receive and store your name, your email address or Apple private relay email address, and identifiers needed to create and maintain your Sted account.</p>
    <p>We also use account identifiers generated by our authentication provider to associate your saved content with your account.</p>
    <h3>Links and content you save</h3>
    <p>When you save a link, we collect the URL you submit.</p>
    <p>We may also retrieve and process information available from the linked resource, such as its canonical URL, domain, title, description, author, publication information, page or post text, and other metadata.</p>
    <p>For supported resources, processing may also involve information such as transcripts or other text associated with the linked resource.</p>
    <p>URLs can themselves contain personal information, identifiers, access parameters, or point to content containing information about you or other people. Please consider this before saving a link to Sted.</p>
    <h3>Projects and organization</h3>
    <p>We store information you create to organize your library, including project names and descriptions and the association between projects and saved items.</p>
    <h3>AI-generated information</h3>
    <p>Sted may generate and store summaries, key ideas, topics, tags, entities, project suggestions or assignments, and other metadata derived from content you save.</p>
    <p>AI-generated information may be incomplete or inaccurate.</p>
    <h3>Technical and operational information</h3>
    <p>When you use Sted, our infrastructure and service providers may process technical information necessary to operate, secure, and troubleshoot the Service, such as IP address, timestamps, authentication events, request metadata, device or browser information made available through network requests, and error or diagnostic information.</p>
    <p>We do not currently use Sted user content for behavioral advertising or cross-company advertising tracking.</p>

    <h2>3. How saved links are processed</h2>
    <p>When you save a link, Sted sends the URL to our backend systems.</p>
    <p>Our systems may attempt to retrieve information from the linked resource. Depending on the resource and what is technically accessible, this may include page text, post text, metadata, or other text associated with the resource.</p>
    <p>Sted stores certain extracted information with the saved item so that the item can be displayed, searched, summarized, and organized in your library.</p>
    <p>The availability and quality of extracted information depend on the linked website or service. Sted may not be able to access or process every link.</p>

    <h2>4. Artificial intelligence and Google Gemini</h2>
    <p>Sted uses <strong>Google Gemini</strong> to provide AI-powered processing.</p>
    <p>If you enable AI processing, Sted may send Google information associated with links you save so that Gemini can generate summaries, tags, topics, metadata, and organization suggestions.</p>
    <p>Information sent for this purpose may include relevant extracted text, transcripts when available, comments or metadata when available, URLs and page metadata, and information about your Sted projects that is needed to organize the saved item.</p>
    <p>Sted does not send this information to Google for behavioral advertising or cross-company tracking.</p>
    <p>Sted uses a paid Gemini API service for production processing. Under Google's applicable terms for Paid Services, Google states that prompts and responses are not used to improve Google's products. Google may nevertheless retain or process limited information for security, abuse prevention, legal, or operational purposes in accordance with its applicable terms.</p>
    <p>You can decline or later disable AI processing. If AI processing is disabled, Sted will not send new saved content to Google Gemini for AI analysis. Features that depend on AI processing, including automatic summaries, tags, and project organization, may not be available for those items.</p>

    <h2>5. How we use information</h2>
    <p>We use information to:</p>
    <ul>
      <li>create, authenticate, and maintain your account;</li>
      <li>save and display the links you choose to add;</li>
      <li>retrieve and process information associated with saved links;</li>
      <li>generate summaries, tags, topics, and organization when AI processing is enabled;</li>
      <li>organize and search your personal library;</li>
      <li>maintain, secure, troubleshoot, and improve the reliability of the Service;</li>
      <li>respond to support requests;</li>
      <li>prevent misuse, fraud, and security incidents; and</li>
      <li>comply with applicable law.</li>
    </ul>
    <p>We do not use saved Sted content to build advertising profiles about you.</p>

    <h2>6. Service providers</h2>
    <p>We use third-party service providers to operate Sted.</p>
    <p>These currently include:</p>
    <p><strong>Supabase</strong>, which provides authentication and database infrastructure and processes account information and the data stored in your Sted account.</p>
    <p><strong>Google Cloud</strong>, which provides backend computing and related infrastructure used to operate Sted.</p>
    <p><strong>Google Gemini</strong>, which provides AI processing when you enable AI features as described above.</p>
    <p><strong>Apple</strong>, which provides Sign in with Apple and distributes the iOS application through the App Store.</p>
    <p>These providers may process information on our behalf or as necessary to provide their respective services. Their own contractual and legal obligations also apply to their processing.</p>
    <p>We may update our service providers as the Service develops and will update this Privacy Policy when a change materially affects how your personal information is processed.</p>

    <h2>7. How we share information</h2>
    <p>We may disclose information:</p>
    <ul>
      <li>to service providers that process information to operate Sted;</li>
      <li>when you direct or authorize us to do so;</li>
      <li>when reasonably necessary to comply with law, legal process, or valid governmental requests;</li>
      <li>when reasonably necessary to protect the rights, safety, security, or integrity of Sted, Finiks Labs, our users, or others; or</li>
      <li>in connection with a merger, acquisition, financing, reorganization, or sale of all or part of our business, subject to applicable law.</li>
    </ul>
    <p>We do <strong>not</strong> sell personal information or saved Sted content.</p>
    <p>We do <strong>not</strong> use saved Sted content for third-party behavioral advertising.</p>
    <p>We do <strong>not</strong> use Sted data for cross-company advertising tracking.</p>

    <h2>8. Data retention</h2>
    <p>Account information is generally retained while your Sted account remains active.</p>
    <p>Saved links, extracted content stored with them, projects, summaries, tags, and other generated metadata are generally retained until you delete the applicable content or delete your account.</p>
    <p>Technical, security, diagnostic, and infrastructure records may follow separate retention periods determined by their operational purpose and the configuration of our service providers.</p>
    <p>When information is deleted, limited copies may remain temporarily in backups, logs, or systems used for security, fraud prevention, legal compliance, or disaster recovery, where permitted by law.</p>
    <p>We do not promise that every copy disappears instantaneously from every backup or infrastructure system.</p>

    <h2>9. Account and content deletion</h2>
    <p>You can initiate deletion of your Sted account from within the Sted application through <strong>Settings → Delete Account</strong>.</p>
    <p>Account deletion is intended to remove your Sted account and associated saved links, projects, extracted content stored with those items, and AI-generated metadata from our active application database, subject to limited retention described above.</p>
    <p>Deleting your Sted account is separate from cancelling an App Store subscription, if Sted offers subscriptions in the future.</p>
    <p>You may also contact us regarding privacy or deletion requests at <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a>.</p>

    <h2>10. AI controls and withdrawing permission</h2>
    <p>You can choose whether Sted sends new saved content to Google Gemini for AI processing.</p>
    <p>You may change this choice in the application's privacy settings.</p>
    <p>Disabling AI processing stops future sharing with Gemini for this purpose. It does not reverse processing that occurred before you withdrew permission or automatically delete summaries or other results already stored in your Sted account.</p>
    <p>You may separately delete saved items or your entire account.</p>

    <h2>11. Security</h2>
    <p>We use reasonable administrative, technical, and organizational measures designed to protect information processed through Sted.</p>
    <p>Our infrastructure providers use security measures that include encryption of network communications and server-side protections. However, no internet service or storage system can guarantee absolute security.</p>
    <p>Sted does not claim that the Service is end-to-end encrypted.</p>

    <h2>12. International processing</h2>
    <p>Finiks Labs LLC is based in the United States, and our service providers may process information in the United States and other countries.</p>
    <p>Where applicable law requires safeguards for international transfers of personal information, we rely on contractual or other lawful transfer mechanisms made available by our service providers, such as applicable data processing agreements and Standard Contractual Clauses.</p>

    <h2>13. Your privacy rights</h2>
    <p>Depending on where you live, you may have rights concerning your personal information, including rights to access, correct, delete, obtain a copy of, restrict, or object to certain processing of your information, or withdraw consent where processing is based on consent.</p>
    <p>To exercise a privacy right, contact <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a>.</p>
    <p>We may need to verify your identity before completing certain requests.</p>
    <p>If you are in the European Economic Area or United Kingdom, Finiks Labs LLC generally acts as the controller of personal information processed to provide your Sted account. Core account and service processing may be necessary to perform our agreement with you, while processing for which we specifically request consent, including third-party AI processing where applicable, is based on that consent. We may also process limited information where necessary for legitimate interests such as securing and maintaining the Service, subject to applicable law.</p>
    <p>You may have the right to lodge a complaint with your local data protection authority.</p>

    <h2>14. California privacy</h2>
    <p>California residents may have rights under applicable California privacy laws, subject to the scope and applicability of those laws.</p>
    <p>Finiks Labs does not sell personal information and does not share personal information for cross-context behavioral advertising as those concepts are commonly used under California privacy law.</p>
    <p>If applicable, you may contact <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a> to exercise your rights.</p>

    <h2>15. Third-party links and content</h2>
    <p>Sted lets you save links to websites and services that we do not operate.</p>
    <p>Their content, availability, privacy practices, and terms are controlled by those third parties. Saving a link in Sted does not make Finiks Labs the operator or publisher of the linked service.</p>
    <p>Please do not use Sted to submit content you are not legally permitted to access or process.</p>

    <h2>16. Children</h2>
    <p>Sted is intended for adults and is not directed to children.</p>
    <p>You must be at least <strong>18 years old</strong> to use Sted.</p>
    <p>If we learn that an account is being used by someone who does not meet this requirement, we may take steps to restrict or delete the account as appropriate.</p>

    <h2>17. Changes to this Privacy Policy</h2>
    <p>We may update this Privacy Policy as Sted or our practices change.</p>
    <p>If a change materially affects how we process information or requires new permission, we will provide additional notice or obtain permission where required.</p>
    <p>The “Last updated” date above identifies the current version.</p>

    <h2>18. Contact</h2>
    <address><strong>Finiks Labs LLC</strong><br />30 N Gould St Ste R<br />Sheridan, WY 82801<br />United States</address>
    <p><a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a></p>
  </>
}

function TermsOfUse() {
  return <>
    <p>These Terms of Use (“Terms”) govern your access to and use of Sted, including the Sted iOS application, Share Extension, sted.ai, and related services (collectively, the “Service”).</p>
    <p>The Service is operated by <strong>Finiks Labs LLC</strong>, a Wyoming limited liability company (“Finiks Labs,” “Sted,” “we,” “us,” or “our”).</p>
    <p>By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use Sted.</p>

    <h2>1. Eligibility</h2>
    <p>You must be at least 18 years old and legally able to enter into these Terms to use Sted.</p>
    <p>You may not use the Service if applicable law prohibits you from doing so.</p>

    <h2>2. Your account</h2>
    <p>Sted currently uses Sign in with Apple to authenticate users.</p>
    <p>You are responsible for maintaining control of the Apple account and devices you use to access Sted and for activity occurring through your Sted account.</p>
    <p>You may delete your Sted account through the account settings in the application.</p>

    <h2>3. What Sted does</h2>
    <p>Sted lets you save links and organize information associated with those links.</p>
    <p>When you save a link, Sted may retrieve information from the linked resource and, when you have enabled AI processing, use artificial intelligence to generate summaries, tags, topics, project organization, and other metadata.</p>
    <p>Not every link can be accessed or processed successfully. Websites and third-party services may change, restrict access, remove content, or make information unavailable.</p>

    <h2>4. Your content</h2>
    <p>For purposes of these Terms, “User Content” includes links you save, project names and descriptions you create, and other information you intentionally provide through Sted.</p>
    <p>As between you and Finiks Labs, you retain any rights you have in your User Content.</p>
    <p>You give Finiks Labs a limited, non-exclusive license to host, copy, retrieve, process, transmit, transform, and display User Content only as reasonably necessary to operate, secure, maintain, and provide the Service to you.</p>
    <p>This license ends when the relevant User Content is deleted from the Service, subject to reasonable technical retention in backups, logs, security systems, or as otherwise permitted or required by law.</p>

    <h2>5. Links and third-party content</h2>
    <p>Sted can process links to websites and services operated by third parties.</p>
    <p>You are responsible for ensuring that your use of Sted, including your submission of a link or resource, complies with applicable law and that you are authorized to access and use the resource in the manner you request.</p>
    <p>You may not use Sted to circumvent access controls, authentication requirements, paywalls, technical protection measures, or other restrictions you are not authorized to bypass.</p>
    <p>Linked content remains subject to the rights, terms, and policies of its owner or operator.</p>
    <p>Sted does not claim ownership of third-party material merely because you save or process a link to it.</p>

    <h2>6. AI-generated output</h2>
    <p>Sted uses artificial intelligence for features such as summarization, classification, tagging, and organization.</p>
    <p>AI-generated output may be incomplete, inaccurate, outdated, misleading, or otherwise incorrect.</p>
    <p>You are responsible for reviewing and verifying information before relying on it for important decisions.</p>
    <p>Sted is a productivity tool and does not provide legal, medical, financial, or other professional advice.</p>
    <p>Your use of AI features is also subject to the privacy disclosures and choices described in the Sted Privacy Policy.</p>

    <h2>7. Acceptable use</h2>
    <p>You may not use Sted:</p>
    <ul>
      <li>in violation of applicable law;</li>
      <li>to access or process material you are not authorized to access;</li>
      <li>to infringe intellectual property, privacy, publicity, or other rights;</li>
      <li>to distribute malware or malicious code;</li>
      <li>to interfere with or disrupt Sted or its infrastructure;</li>
      <li>to attempt unauthorized access to accounts, systems, or networks;</li>
      <li>to circumvent technical limits or security measures;</li>
      <li>to use automated methods that materially burden or abuse the Service;</li>
      <li>to use the Service to facilitate fraud, unlawful activity, or abuse; or</li>
      <li>in a manner prohibited by applicable third-party service terms governing content you submit.</li>
    </ul>
    <p>We may restrict or suspend access where reasonably necessary to protect Sted, our users, third parties, or the Service.</p>

    <h2>8. Intellectual property</h2>
    <p>Except for User Content and third-party materials, the Service, including its software, design, branding, graphics, and other content, is owned by Finiks Labs or its licensors and is protected by applicable intellectual-property laws.</p>
    <p>These Terms do not grant you ownership of Sted or any right to use Sted trademarks except as expressly permitted by us.</p>

    <h2>9. Privacy</h2>
    <p>Our Privacy Policy explains how we process personal information and is incorporated into these Terms by reference.</p>
    <p>Certain features, including third-party AI processing, may require a separate permission or choice.</p>

    <h2>10. Third-party services</h2>
    <p>Sted relies on third-party services to provide portions of the Service, including authentication, hosting, database infrastructure, and artificial-intelligence processing.</p>
    <p>Those services may become unavailable or change, and their applicable terms and policies govern their own services.</p>
    <p>Sted may also contain or process links to third-party websites. Finiks Labs does not control and is not responsible for the availability, accuracy, security, content, or practices of third-party websites.</p>

    <h2>11. Paid features</h2>
    <p>Sted may offer paid features or subscriptions in the future.</p>
    <p>If paid features are offered through Apple's App Store, the price, billing period, renewal terms, and cancellation information shown to you at purchase will apply, together with Apple's applicable payment terms.</p>
    <p>Nothing in these Terms represents that a paid feature or subscription is currently available unless it is actually offered in the version of Sted you are using.</p>

    <h2>12. Changes to the Service</h2>
    <p>Sted is an evolving product.</p>
    <p>We may add, modify, suspend, or discontinue features or portions of the Service. We do not promise that any roadmap item, prototype, planned feature, or future integration will be released.</p>

    <h2>13. Termination</h2>
    <p>You may stop using Sted at any time and may delete your account through the application.</p>
    <p>We may suspend or terminate access when reasonably necessary because of material violation of these Terms, legal requirements, security concerns, abuse, or conduct that creates material risk to Sted or others.</p>
    <p>Provisions that by their nature should survive termination, including intellectual-property provisions, disclaimers, limitations of liability, and dispute provisions, survive as applicable.</p>

    <h2>14. Disclaimers</h2>
    <p>To the fullest extent permitted by applicable law, the Service is provided on an “as is” and “as available” basis.</p>
    <p>We do not guarantee that Sted will always be uninterrupted, error-free, secure, or able to retrieve or process every link.</p>
    <p>We do not guarantee that extracted information or AI-generated summaries, tags, classifications, or other outputs will be complete or accurate.</p>
    <p>Nothing in these Terms excludes warranties or rights that cannot lawfully be excluded.</p>

    <h2>15. Limitation of liability</h2>
    <p>To the fullest extent permitted by applicable law, Finiks Labs LLC will not be liable for indirect, incidental, special, consequential, exemplary, or similar damages arising from or relating to the Service.</p>
    <p>Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited.</p>

    <h2>16. Copyright concerns</h2>
    <p>If you believe content processed or made available through Sted infringes your copyright or other intellectual-property rights, contact us at <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a> with sufficient information for us to understand and investigate the concern.</p>
    <p>Because Sted libraries are private by default and Sted is not currently a public content-publishing platform, we may adapt our copyright complaint process as the Service develops.</p>

    <h2>17. Changes to these Terms</h2>
    <p>We may update these Terms from time to time.</p>
    <p>If a change materially affects your rights or requires additional consent, we will provide notice where required.</p>
    <p>Continued use of the Service after an applicable update takes effect constitutes acceptance to the extent permitted by law.</p>

    <h2>18. Governing law</h2>
    <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict-of-laws principles, except to the extent mandatory law in your place of residence provides otherwise.</p>

    <h2>19. Contact</h2>
    <address><strong>Finiks Labs LLC</strong><br />30 N Gould St Ste R<br />Sheridan, WY 82801<br />United States</address>
    <p><a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a></p>
  </>
}

export function LegalPage({ document }: { document: LegalDocument }) {
  const isPrivacy = document === 'privacy'

  return <div id="top" className="min-h-screen legal-page">
    <header className="site-header shell">
      <Logo />
      <a className="button button-outline header-cta" href="/">Back to Sted</a>
    </header>
    <main className="legal-content shell">
      <p className="section-label">FINIKS LABS LLC</p>
      <h1>{isPrivacy ? 'Privacy Policy' : 'Terms of Use'}</h1>
      <p className="legal-date"><strong>Last updated: August 28, 2026</strong></p>

      {isPrivacy ? <PrivacyPolicy /> : <TermsOfUse />}

      <div className="legal-switch"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div>
    </main>
  </div>
}
