import { Logo } from './logo'

export type LegalDocument = 'privacy' | 'terms'

function PrivacyPolicy() {
  return <>
    <p>Sted is operated by <strong>Finiks Labs LLC</strong>, a Wyoming limited liability company (“Finiks Labs,” “Sted,” “we,” “us,” or “our”).</p>
    <p>This Privacy Policy explains how we collect, use, disclose, and otherwise process information when you use the Sted iOS application, Share Extension, sted.ai, and related services (collectively, the “Service”).</p>

    <h2>1. What Sted does</h2>
    <p>Sted helps you save and organize links and information associated with those links.</p>
    <p>When you save a link, Sted may retrieve information associated with the linked resource and, if AI processing is enabled for your account, use third-party artificial-intelligence services to generate information such as titles, summaries, key ideas, classifications, tags, topics, entities, and project organization or suggestions.</p>
    <p>Saved content and information generated from it are associated with your Sted account.</p>
    <p>The current iOS application is designed primarily around links and information associated with those links. It does not currently provide general-purpose direct uploads of photographs, raw video files, microphone recordings, or arbitrary personal files for AI processing.</p>

    <h2>2. Information we collect</h2>
    <h3>Account information</h3>
    <p>Sted currently uses <strong>Sign in with Apple</strong>.</p>
    <p>Depending on the information you choose to share through Apple, we may receive your name, email address or Apple private relay email address, and identifiers needed to create, authenticate, and maintain your Sted account.</p>
    <p>We also use account identifiers generated by our authentication infrastructure to associate your saved content with your account.</p>
    <h3>Links and content you save</h3>
    <p>When you save a link, we collect the URL you submit.</p>
    <p>We may retrieve and process information available from the linked resource, such as:</p>
    <ul>
      <li>canonical URL and domain;</li>
      <li>title and description;</li>
      <li>author or publication information;</li>
      <li>page or post text;</li>
      <li>metadata;</li>
      <li>transcripts when available;</li>
      <li>comments or other text associated with a resource when available; and</li>
      <li>other information necessary to identify, display, understand, or organize the saved resource.</li>
    </ul>
    <p>URLs can themselves contain identifiers or other information. The content you save may also contain information about you or other people. You should only save or process links that you are authorized to access and use.</p>
    <h3>Projects, notes, and organization</h3>
    <p>We store information you create to organize your library, including project names and descriptions, notes or topics you add, and associations between projects and saved items.</p>
    <h3>Generated information</h3>
    <p>Sted may generate and store titles, summaries, key ideas, topics, tags, entities, classifications, project suggestions or assignments, and other metadata derived from content you save.</p>
    <p>Generated information may be incomplete or inaccurate.</p>
    <h3>Website, waitlist, and communications</h3>
    <p>If you join a Sted waitlist or provide your email address through sted.ai, we collect the email address you provide. We may also record limited information associated with the submission, such as a referral or source value where applicable.</p>
    <p>If you contact us, we receive the information you choose to include in your message, such as your email address and the contents of your communication.</p>
    <h3>Technical and operational information</h3>
    <p>When you use Sted, we and our infrastructure providers may process technical and operational information necessary to provide, secure, maintain, and troubleshoot the Service.</p>
    <p>This may include information such as IP address, timestamps, authentication events, request information, network information, and error or diagnostic information made available through ordinary use of our systems.</p>

    <h2>3. How saved links are processed</h2>
    <p>When you save a link, Sted sends the URL to our backend.</p>
    <p>Our systems may attempt to retrieve information associated with the linked resource. Depending on the resource and what is technically available, this may include text, metadata, transcripts, comments, or other information associated with that resource.</p>
    <p>Some extracted information is stored with the saved item so that Sted can display, search, summarize, classify, and organize it.</p>
    <p>The availability and quality of information depend on the linked website or service. Sted cannot access or fully process every link.</p>

    <h2>4. How we use information</h2>
    <p>We use information to:</p>
    <ul>
      <li>create, authenticate, and maintain Sted accounts;</li>
      <li>save and display links you choose to add;</li>
      <li>retrieve information associated with saved links;</li>
      <li>provide search and organization features;</li>
      <li>generate titles, summaries, classifications, key ideas, topics, tags, entities, and project organization or suggestions when AI processing is enabled;</li>
      <li>maintain, secure, troubleshoot, and improve the reliability of the Service;</li>
      <li>respond to support requests;</li>
      <li>prevent misuse, fraud, and security incidents; and</li>
      <li>comply with applicable law.</li>
    </ul>
    <h3>Legal bases for EEA and UK users</h3>
    <p>Where the EU GDPR or UK GDPR applies to our processing, the legal basis depends on the purpose of the processing:</p>
    <ul>
      <li><strong>Contract:</strong> to create and authenticate your account and provide the core Sted features you request, including saving, retrieving, displaying, searching, and organizing your content.</li>
      <li><strong>Consent:</strong> for AI processing that is enabled only after you give the applicable permission. You may withdraw that permission by turning AI processing off in Settings. Withdrawal does not affect processing that occurred before you withdrew permission.</li>
      <li><strong>Legitimate interests:</strong> to operate, secure, troubleshoot, and improve the reliability of the Service, prevent fraud and misuse, and respond to support requests, where those interests are not overridden by your rights and interests.</li>
      <li><strong>Legal obligations:</strong> where processing is necessary for us to comply with applicable law, legal process, or enforceable governmental requests.</li>
    </ul>

    <h2>5. Artificial intelligence</h2>
    <p>Sted uses third-party artificial-intelligence services to provide features related to the content you save.</p>
    <p><strong>AI processing is not enabled for your account until you give the applicable permission.</strong> You can subsequently turn AI processing off in Sted Settings.</p>
    <p>When AI processing is enabled, Sted may send saved-content information and related project information to third-party AI service providers so they can generate titles, summaries, classifications, key ideas, tags, topics, entities, and organization or project suggestions.</p>
    <p>Information processed for this purpose may include:</p>
    <ul>
      <li>URLs and page metadata;</li>
      <li>extracted page or post text;</li>
      <li>transcripts when available;</li>
      <li>comments or other associated text when available;</li>
      <li>titles, descriptions, authors, and publication information; and</li>
      <li>relevant Sted project names and descriptions.</li>
    </ul>
    <h3>Current AI routing</h3>
    <p>Sted currently uses <strong>OpenRouter</strong> as an AI routing provider. OpenRouter receives the information included in an AI request and forwards the request to an eligible downstream provider that can serve the AI model selected by Sted.</p>
    <p>For the model Sted currently selects through OpenRouter, OpenRouter currently identifies <strong>OpenAI, Microsoft Azure, and Amazon Web Services (Amazon Bedrock)</strong> as available hosting providers. The downstream provider that processes a particular request may vary according to Sted’s routing configuration, provider availability, and the configuration of the OpenRouter service.</p>
    <p>OpenRouter and downstream providers may process technical and operational information associated with AI requests. Their retention and data-handling practices may differ by provider and configuration. Sted does not represent that AI requests are subject to zero retention or that no technical or operational data is retained.</p>
    <p>We may change the AI model, routing configuration, or service providers used by Sted as the Service develops. If a change materially changes what information is shared, why it is shared, or otherwise requires additional notice or permission under applicable law or Apple requirements, we will update our disclosures or obtain additional permission as required.</p>
    <p>Turning AI processing off prevents Sted from sending newly processed saved-content information for AI analysis while the setting is off. Features that depend on AI processing may not be available for those items.</p>
    <p>Turning AI processing off does not reverse processing that occurred before you changed the setting and does not automatically delete titles, summaries, classifications, tags, or other information already stored in your Sted account. You can separately delete saved items or your account.</p>

    <h2>6. Service providers</h2>
    <p>We use service providers and other third parties to operate Sted. Current material providers include:</p>
    <p><strong>Supabase</strong> — authentication and database infrastructure. Supabase processes information needed for Sted accounts and information stored in users’ Sted accounts. It is also currently used to store Sted website waitlist submissions where applicable.</p>
    <p><strong>Google Cloud</strong> — backend infrastructure used to operate and process Sted requests, including backend computing and asynchronous processing.</p>
    <p><strong>OpenRouter</strong> — AI request routing and access to third-party AI models when AI processing is enabled. As described above, OpenRouter may forward an AI request to an eligible downstream model-hosting provider.</p>
    <p><strong>Apple</strong> — Sign in with Apple and distribution of the iOS application through the App Store.</p>
    <p><strong>Cloudflare</strong> — infrastructure used to host and deliver the Sted website.</p>
    <p>Some providers process information on our behalf, while others process information under their own applicable terms and legal obligations.</p>
    <p>We may replace or add service providers as Sted develops. If a change materially affects how personal information is processed, we will update this Privacy Policy or provide additional notice or permission where required.</p>

    <h2>7. How we disclose information</h2>
    <p>We may disclose information:</p>
    <ul>
      <li>to service providers and other third parties that help operate the Service, including AI providers when AI processing is enabled;</li>
      <li>when you direct or authorize us to do so;</li>
      <li>where reasonably necessary to comply with law, legal process, or valid governmental requests;</li>
      <li>where reasonably necessary to protect the rights, safety, security, or integrity of Sted, Finiks Labs, our users, or others; or</li>
      <li>in connection with a merger, acquisition, financing, reorganization, or sale of all or part of our business, subject to applicable law.</li>
    </ul>

    <h2>8. External websites and in-app web viewing</h2>
    <p>Sted lets you open saved links and may display external websites in an in-app web viewer.</p>
    <p>External websites are operated by third parties, not by Finiks Labs. When you load or navigate a third-party website, that website may receive information directly from your device, such as your IP address, browser or device information, cookies, or information you provide to that website, according to its own privacy practices.</p>
    <p>Sted does not control the content, availability, security, terms, or privacy practices of third-party websites.</p>

    <h2>9. Advertising</h2>
    <p>Sted does <strong>not currently use saved content to serve personalized advertising</strong>.</p>
    <p>We do not currently sell personal information or share personal information for cross-context behavioral advertising.</p>
    <p>If Sted introduces advertising, sponsorships, or materially different uses of information for advertising in the future, we will update this Privacy Policy and obtain additional permission where required.</p>

    <h2>10. Data retention</h2>
    <p>Account information is generally retained while your Sted account remains active.</p>
    <p>Saved links, stored extracted information, projects, notes, generated information, and related account data are generally retained until you delete the applicable content or delete your account.</p>
    <p>Technical, security, diagnostic, AI-provider, and infrastructure information may be retained according to its operational purpose and the systems or service providers involved.</p>
    <p>After deletion, limited information may remain temporarily in backups, logs, security systems, or records retained where permitted or required by law.</p>
    <p>We do not promise that every copy disappears instantaneously from every infrastructure system.</p>

    <h2>11. Account and content deletion</h2>
    <p>You can initiate deletion of your Sted account from within the iOS application through <strong>Settings → Delete Account</strong>.</p>
    <p>Account deletion removes your Sted account and associated saved items, projects, stored extracted information, user-created organization data, settings, and generated information from Sted’s active application database, subject to the limited retention described above.</p>
    <p>Where applicable, Sted also attempts to revoke credentials associated with Sign in with Apple as part of the account-deletion process.</p>
    <p>You may also contact us regarding privacy or deletion requests at <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a>.</p>

    <h2>12. Security</h2>
    <p>We use reasonable administrative, technical, and organizational measures designed to protect information processed through Sted.</p>
    <p>No internet service, transmission method, or storage system can guarantee absolute security.</p>
    <p>Sted does not represent that the Service is end-to-end encrypted.</p>

    <h2>13. International processing</h2>
    <p>Finiks Labs LLC is based in the United States.</p>
    <p>Our service providers may process information in the United States and other countries.</p>
    <p>Where applicable law requires safeguards for international transfers, we use or rely on appropriate lawful transfer mechanisms available for the relevant processing. These may include adequacy decisions, contractual safeguards such as the European Commission's Standard Contractual Clauses, and applicable United Kingdom transfer mechanisms. You may contact <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a> for information about safeguards applicable to a particular transfer.</p>

    <h2>14. Your privacy rights</h2>
    <p>Depending on where you live, applicable law may give you rights concerning your personal information, which may include rights to access, correct, delete, obtain a copy of, restrict, or object to certain processing, or withdraw permission where applicable.</p>
    <p>To exercise an applicable privacy right, contact <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a>.</p>
    <p>We may need to verify your identity before completing certain requests.</p>
    <p>Where applicable, you may also have the right to complain to your local privacy or data-protection authority. If the EU GDPR applies, you may lodge a complaint with a supervisory authority in the EEA. If the UK GDPR applies, you may lodge a complaint with the UK Information Commissioner's Office.</p>
    <p>California residents may have additional rights where applicable. Sted does not currently sell personal information or share personal information for cross-context behavioral advertising.</p>

    <h2>15. Age eligibility</h2>
    <p>Sted is not directed to children under <strong>16 years old</strong>, and users under 16 may not use Sted.</p>
    <p>Users who are 16 or 17 may use Sted only with the permission of a parent or legal guardian and where permitted by applicable law.</p>
    <p>If we learn that an account is being used by someone who is not eligible to use Sted under these requirements, we may take appropriate steps to restrict the account or delete information as appropriate.</p>

    <h2>16. Third-party links and content</h2>
    <p>Sted lets you save and view links to websites and services that we do not operate.</p>
    <p>Their content, availability, privacy practices, and terms are controlled by those third parties.</p>
    <p>Saving or displaying a third-party link in Sted does not make Finiks Labs the operator or publisher of that service.</p>

    <h2>17. Changes to this Privacy Policy</h2>
    <p>We may update this Privacy Policy as Sted, our providers, or our practices change.</p>
    <p>If a change materially affects how we process personal information or requires new permission, we will provide additional notice or obtain permission where required.</p>
    <p>The “Last updated” date identifies the current version.</p>

    <h2>18. Contact</h2>
    <address><strong>Finiks Labs LLC</strong><br />30 N Gould St Ste R<br />Sheridan, WY 82801<br />United States</address>
    <p><a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a></p>
  </>
}

function TermsOfUse() {
  return <>
    <p>These Terms of Service (“Terms”) govern your access to and use of Sted, including the Sted iOS application, Share Extension, sted.ai, and related services (collectively, the “Service”).</p>
    <p>The Service is operated by <strong>Finiks Labs LLC</strong>, a Wyoming limited liability company (“Finiks Labs,” “Sted,” “we,” “us,” or “our”).</p>
    <p>By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use Sted.</p>

    <h2>1. Eligibility</h2>
    <p>You must be at least <strong>16 years old</strong> to use Sted.</p>
    <p>If you are under 18, you may use Sted only with the permission of a parent or legal guardian and only where your use of the Service is permitted by applicable law.</p>
    <p>You may not use the Service if applicable law prohibits you from doing so.</p>

    <h2>2. Your account</h2>
    <p>Sted currently uses <strong>Sign in with Apple</strong> to authenticate users.</p>
    <p>You are responsible for maintaining control of the Apple account and devices you use to access Sted and for activity occurring through your Sted account.</p>
    <p>You may delete your Sted account from within the application.</p>

    <h2>3. What Sted does</h2>
    <p>Sted helps you save links and organize information associated with those links.</p>
    <p>When you save a link, Sted may retrieve information from the linked resource, store information associated with it, and use automated systems, including artificial intelligence, to provide features such as titles, summaries, classifications, tags, topics, key ideas, entity identification, search, and project organization or suggestions.</p>
    <p>Not every link can be accessed or processed successfully. Websites and third-party services may change, restrict access, remove content, or make information unavailable.</p>

    <h2>4. Your content</h2>
    <p>For purposes of these Terms, “User Content” includes links you save, notes or topics you add, project names and descriptions you create, and other information you intentionally provide through Sted.</p>
    <p>As between you and Finiks Labs, you retain any rights you have in your User Content.</p>
    <p>You give Finiks Labs a limited, non-exclusive license to host, copy, retrieve, process, transmit, transform, and display User Content, including through service providers acting on our behalf, only as reasonably necessary to operate, secure, maintain, and provide the Service to you.</p>
    <p>This license ends when the relevant User Content is deleted from the Service, subject to reasonable technical retention in backups, logs, security systems, or as otherwise permitted or required by law.</p>

    <h2>5. Links, external websites, and third-party content</h2>
    <p>Sted can process and display links to websites and services operated by third parties. Sted may also allow you to view and navigate external web content through an in-app web viewer.</p>
    <p>You are responsible for ensuring that your use of Sted, including links or resources you submit, complies with applicable law and that you are authorized to access and use those resources in the manner you request.</p>
    <p>You may not use Sted to circumvent access controls, authentication requirements, paywalls, technical protection measures, or other restrictions that you are not authorized to bypass.</p>
    <p>Linked content remains subject to the rights, terms, and policies of its owner or operator. Third-party websites may collect information directly from your device when you visit them, according to their own terms and privacy practices.</p>
    <p>Sted does not claim ownership of third-party material merely because you save, view, or process a link to it.</p>

    <h2>6. Artificial intelligence</h2>
    <p>Sted may use third-party artificial intelligence services to process, analyze, summarize, classify, organize, and otherwise provide features related to content you save.</p>
    <p>Depending on the features and settings you use, saved content and related information may be processed by third-party AI and infrastructure providers as described in the Sted Privacy Policy.</p>
    <p>AI processing is enabled only after the applicable user permission is obtained. You may subsequently control AI processing through the settings available in the Service.</p>
    <p>AI-generated output may be incomplete, inaccurate, outdated, or otherwise incorrect. You should review information before relying on it for important decisions.</p>
    <p>Sted is a productivity tool and does not provide legal, medical, financial, or other professional advice.</p>
    <p>Your use of AI-enabled features must also comply with any applicable usage restrictions or terms imposed by the AI or model providers used to provide those features.</p>

    <h2>7. Acceptable use</h2>
    <p>You may not use Sted:</p>
    <ul>
      <li>in violation of applicable law;</li>
      <li>to access or process material you are not authorized to access or process;</li>
      <li>to infringe intellectual property, privacy, publicity, or other rights;</li>
      <li>to distribute malware or malicious code;</li>
      <li>to interfere with or disrupt Sted or its infrastructure;</li>
      <li>to attempt unauthorized access to accounts, systems, or networks;</li>
      <li>to circumvent technical limits or security measures;</li>
      <li>to use automated methods that materially burden or abuse the Service;</li>
      <li>to facilitate fraud, unlawful activity, or abuse; or</li>
      <li>in a manner prohibited by applicable third-party terms governing content or AI services used through the Service.</li>
    </ul>
    <p>We may restrict or suspend access where reasonably necessary to protect Sted, our users, third parties, or the Service.</p>

    <h2>8. Sted intellectual property</h2>
    <p>Except for User Content and third-party materials, the Service, including its software, design, branding, graphics, and other content, is owned by Finiks Labs or its licensors and is protected by applicable intellectual-property laws.</p>
    <p>These Terms do not grant you ownership of Sted or any right to use Sted trademarks except as expressly permitted by us.</p>

    <h2>9. Privacy and data processing</h2>
    <p>Our Privacy Policy explains how Sted collects, uses, and shares information and the choices available to you.</p>
    <p>Certain processing, including sharing saved-content information with third-party AI service providers, depends on the permission and settings applicable to your account.</p>

    <h2>10. Third-party services</h2>
    <p>Sted relies on third-party services for portions of the Service, including authentication, hosting, database infrastructure, website delivery, and artificial-intelligence processing.</p>
    <p>Providers may change over time. Their own applicable terms and policies govern their services.</p>
    <p>Sted may also contain or display links to third-party websites. Finiks Labs does not control and is not responsible for the availability, accuracy, security, content, or practices of third-party websites.</p>

    <h2>11. Paid features</h2>
    <p>Sted may offer paid features or subscriptions.</p>
    <p>If a purchase is offered through Apple’s App Store, the pricing, billing, renewal, cancellation, and other purchase information shown at the time of purchase will apply together with Apple’s applicable payment terms.</p>
    <p>Nothing in these Terms represents that any particular paid feature or subscription is currently available unless it is actually offered in the version of Sted you are using.</p>

    <h2>12. Changes to the Service</h2>
    <p>Sted is an evolving product.</p>
    <p>We may add, modify, suspend, or discontinue features or portions of the Service.</p>
    <p>We do not promise that any roadmap item, prototype, planned feature, integration, model, or service provider will remain available or be released.</p>

    <h2>13. Termination and account deletion</h2>
    <p>You may stop using Sted at any time and may delete your account through the application.</p>
    <p>We may suspend or terminate access when reasonably necessary because of a material violation of these Terms, legal requirements, security concerns, abuse, or conduct that creates material risk to Sted or others.</p>
    <p>Account deletion is handled as described in our Privacy Policy.</p>
    <p>Provisions that by their nature should survive termination, including intellectual-property provisions, disclaimers, limitations of liability, and dispute provisions, survive as applicable.</p>

    <h2>14. Disclaimers</h2>
    <p>To the fullest extent permitted by applicable law, the Service is provided on an “as is” and “as available” basis.</p>
    <p>We do not guarantee that Sted will always be uninterrupted, error-free, secure, or able to retrieve or process every link.</p>
    <p>We do not guarantee that extracted information, AI-generated titles, summaries, classifications, tags, topics, project suggestions, or other outputs will be complete or accurate.</p>
    <p>Nothing in these Terms excludes warranties or consumer rights that cannot lawfully be excluded.</p>

    <h2>15. Limitation of liability</h2>
    <p>To the fullest extent permitted by applicable law, Finiks Labs LLC will not be liable for indirect, incidental, special, consequential, exemplary, or similar damages arising from or relating to the Service.</p>
    <p>Nothing in these Terms excludes or limits liability that cannot legally be excluded or limited.</p>

    <h2>16. Copyright and intellectual-property concerns</h2>
    <p>If you believe content processed or made available through Sted infringes your copyright or other intellectual-property rights, contact us at <a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a> with sufficient information for us to understand and investigate the concern.</p>

    <h2>17. Apple Standard EULA</h2>
    <p>The license to use the Sted iOS application is also subject to Apple’s applicable <strong>Standard Licensed Application End User License Agreement</strong>.</p>
    <p>These Terms govern your Sted account and the Sted Service and do not replace Apple’s Standard EULA.</p>

    <h2>18. Changes to these Terms</h2>
    <p>We may update these Terms from time to time.</p>
    <p>If a change materially affects your rights or requires additional permission, we will provide notice or obtain permission where required.</p>
    <p>Continued use after an applicable update takes effect constitutes acceptance to the extent permitted by law.</p>

    <h2>19. Governing law</h2>
    <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict-of-laws principles, except to the extent mandatory law in your place of residence provides otherwise.</p>

    <h2>20. Contact</h2>
    <address><strong>Finiks Labs LLC</strong><br />30 N Gould St Ste R<br />Sheridan, WY 82801<br />United States</address>
    <p><a className="legal-email" href="mailto:hello@sted.ai">hello@sted.ai</a></p>
  </>
}

export function LegalPage({ document }: { document: LegalDocument }) {
  const isPrivacy = document === 'privacy'

  return <div id="top" className="min-h-screen legal-page">
    <header className="site-header shell">
      <Logo />
      <a className="button button-outline header-cta" href="/">Back to Sted</a>
    </header>
    <main className="legal-content shell">
      <p className="section-label">FINIKS LABS LLC</p>
      <h1>{isPrivacy ? 'Privacy Policy' : 'Terms of Use'}</h1>
      <p className="legal-date"><strong>Last updated: September 1, 2026</strong></p>

      {isPrivacy ? <PrivacyPolicy /> : <TermsOfUse />}

      <div className="legal-switch"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div>
    </main>
  </div>
}
